version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
      # not sure abot the following line:
      - ./scripts/db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  api:
    build: ./api
    ports:
      - "6969:6969"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: appdb

  frontend:
    image: nginx:stable-alpine
    volumes:
      - ./public:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - api

# forgot why i put it here
volumes:
  db_data:
